import {Link} from 'react-router-dom'

function Ruang() {
  return (
    <div className = "bg-pinkLight p-3">
    <p className = "font-bold mb-3 text-lg">Ruang dan Interaksi Antar Ruang</p>
      <p>Setiap makhluk hidup yang ada di bumi ini memerlukan ruang untuk melangsungkan kehidupannya. Konsep tentang ruang merupakan salah satu yang harus dipahami dalam mempelajari geografi. Konsep ruang ialah salah satu konsep dalam geografi yang paling mendasar atau fundamental. Velvet Nelson dalam An Introduction to the Geography of Tourism (2013) menjelaskan bahwa geografi dapat disebut sebagai ilmu keruangan (spatial science). Konsep ruang digunakan untuk mempelajari keseluruhan berbagai fenomena yang berada di atas permukaan bumi.</p>
      <p className = "font-bold mt-3">Pengertian Ruang</p>
      <p>Dalam Studi Geografi: Suatu Pendekatan dan Analisa Keruangan (1981), Nursid Sumaatmadja menjabarkan definisi ruang. Ruang adalah tempat di permukaan bumi, baik secara keseluruhan maupun hanya sebagian yang digunakan makhluk hidup untuk tinggal. Ruang juga dapat diartikan sebagai wadah dari semua aktivitas manusia, hewan, tumbuhan yang ada di permukaan bumi. Ruang tidak hanya sebatas udara yang bersentuhan dengan permukaan bumi. Tapi juga lapisan atmosfer terbawah yang memengaruhi permukaan bumi. Ruang juga mencakup perairan yang terdapat di permukaan bumi yaitu laut, sungai, danau, ataupun yang ada di bawah permukaan bumi (air tanah) sampai ke kedalaman tertentu. Dikutip dari Education Standards, konsep ruang adalah konsep yang berfokus pada lokasi dan distribusi keruangan, serta cara orang mengatur dan mengelola ruang yang ditinggali. Karakteristik lingkungan dan manusia dipengaruhi oleh lokasi mereka.</p>
      <p className = "font-bold mt-3">Pengertian interaksi antar ruang</p>
      <p>Setiap ruang di permukaan bumi memiliki ciri khas tertentu yang berbeda antara suatu wilayah dengan wilayah yang lain. Tidak ada satu ruangpun yang mempu memenuhi seluruh kebutuhannya sendiri. Setiap ruang membutuhkan ruang lainnya untuk memenuhi kebutuhan hidup. Perbedaan karakteristik ruang tersebut menyebabkan adanya interaksi antarsatu ruang dengan yang lainnya. Termasuk komunikasi antar manusia yang tinggal di dalamnya. Interaksi merupakan suatu proses yang sifatnya timbal balik dan mempunyai pengaruh terhadap tingkah laku, baik melalui kontak langsung atau tidak langsung. Interaksi antarruang adalah suatu cara mengelola ruang-ruang berdasarkan potensi juga permasalahannya dan keterkaitan suatu ruang dengan ruang-ruang di sekitarnya. Interaksi antarruang dapat berupa pergerakan orang, barang, atau informasi dari daerah asal menuju daerah tujuan atau dari suatu daerah ke daerah lain.</p>
      <p className = "font-bold mt-3">Syarat-syarat interaksi antarruang</p>
      <p>Ada beberapa kondisi saling bergantung yang diperlukan untuk terjadinya interaksi antarruang atau interaksi keruangan, yaitu: 1. Saling melengkapi (complementarity) Antara suatu ruang dengan ruang lain saling membutuhkan sehingga saling melengkapi. Kondisi saling melengkapi dapat terjadi bila antara satu daerah dengan daerah lain menghasilkan komoditas yang berbeda. 2. Kesempatan antara (intervening opportunity) Kesempatan antara maksudnya adalah penawaran alternatif, di mana sebuah ruang menawarkan pilihan yang lebih baik dari ruang asal atau ruang tujuannya. 3. Kemudahan tranfer (transferability). Tranfserability juga dapat diartikan sebagai keadaan yang dapat diserahkan atau dipindahkan. Syarat interaksi antarruang ini sangat penting dalam menciptakan interaksi antarruang. Banyak cara untuk berpindah atau bergeser ke suatu ruang. Syarat ini juga memerlukan biaya.</p>
      <p className = "font-bold mt-3">Bentuk-bentuk interaksi antarruang</p>
      <p>Terdapat tiga bentuk interaksi antarruang, yaitu : 1. Mobilitas penduduk Mobilitas penduduk adalah bentuk interaksi antarruang dalam bentuk pergerakan dan perpindahan manusia dari satu ruang ke ruang lainnya. Contoh: urbanisasi, imigrasi, transmigrasi, perjalanan ke tempat kerja, perjalanan ke tempat wisata, dan lainnya. 2. Komunikasi Komunikasi adalah bentuk interaksi antarruang melalui perpindahan ide, gagasan, informasi,visi misi, cita-cita dan sejenisnya baik secara langsung maupun tidak langsung. Contoh: melihat tayangan berita, melihat tayangan televisi, membaca buku dan lainnya. 3. Transportasi Transportasi adalah bentuk interaksi antarruang melalui perpindahan barang dari suatu tempat ke tempat lain. Contoh: pengangkutan barang, perdagangan, dan lainnya.</p>
      <Link to="/Materi1IPS"><button className="bg-buttonLight mt-12 mx-4 px-4 py-2 rounded-lg text-white">Back</button></Link>
    </div>
  )
}

export default Ruang;